<?php
    $this->setPriceDataObject($this->getSource());
?>
<?php if($this->getSource()->getIsLayaway()): ?>
    <tr>
        <td class="label"><?php echo Mage::helper('layaway')->getLabelsStoredDatafor('remaining') ?></td>
        <td>
            <?php echo "-".$this->displayPrices($this->getSource()->getBaseLayawayRemaining(), $this->getSource()->getLayawayRemaining()); ?>
        </td>
    </tr>
<?php endif; ?>