<?php
    $this->setPriceDataObject($this->getSource());
    $order =  $this->getSource()->getOrder();
?>
<?php if ($order->getIsLayaway()): ?>
    <tr>
        <td class="label"><?php echo Mage::helper('layaway')->getLabelsStoredDatafor('fees') ?></td>
        <td>
            <?php echo $this->displayPrices($order->getBaseLayawayFee(), $order->getLayawayFee()); ?>
        </td>
    </tr>
<?php endif; ?>