<?php $this->setPriceDataObject($this->getSource()) ?>
<?php if ((float) $this->getSource()->getIsLayaway()): ?>
    <tr>
        <td class="label"><?php echo Mage::helper('layaway')->getLabelsStoredDatafor('fees') ?></td>
        <td>
            <?php echo $this->displayPrices($this->getSource()->getBaseLayawayFee(), $this->getSource()->getLayawayFee()); ?>
        </td>
    </tr>
<?php endif; ?>