<?php if($this->getItems()->getSize()): ?>
<div class="block block-related">
    <div class="block-content1">  
        <ul class="mini-products-list" id="block-related">
        <?php //$this->setItemsCount(2);?>
        <?php foreach($this->getItems() as $_item): ?>
        <li class="item">
            <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" 
            class="product-image">
            <img width="115" height="85" 
            src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(115,85) ?>"  
            alt="<?php echo $this->htmlEscape($_item->getName()) ?>" />
            </a>
            <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>">
            <?php echo $this->htmlEscape($_item->getName()) ?></a></p>
            <!--<p class="price"><?php //echo $this->getPriceHtml($_item, true, '-related') ?></p>-->
            <?php $temprelatedprice = $this->helper('catalog/product')->getFinalPrice($_item); ?>
            <p class="price"><span class="price">&pound;<?php echo round($temprelatedprice,2) ?></span></p>
        </li>
        <?php endforeach ?>
        </ul>
    </div>        
</div>
<?php endif ?>