<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Mobile
 * @version    1.6.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php
?>
<?php $_product = $this->getProduct() ?>
<?php if($_product->isSaleable()): ?>
    <p><?php echo $this->__('Availability: In stock.') ?></p>
<?php else: ?>
    <p><?php echo $this->__('Availability: Out of stock.') ?></p>
<?php endif; ?>
<?php echo $this->getChildHtml('product_type_data_extra') ?>
<?php //echo $this->getPriceHtml($_product) ?>

                             <?php 
                                $price = Mage::getModel('catalog/product')->load($_product->getId())->getPrice(); 
                                $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
                                $specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
                                $specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
                                $today =  time();
                                
                                 
                             ?>
                        
                            
                        <?php if ($_product->getPreorder()):?>
                            <?php if ($specialprice): ?>
                                    <div class="listPriceBig">Pre-Order price: <span class="listPriceBigPrice"><?php echo $this->helper('core')->currency($specialprice,true,false); ?></span></div>
                                    <div class="listPriceSmall">Regular price: <span class="listPriceOld"><?php echo $this->helper('core')->currency($price,true,false); ?></span></div>
                                    
                            <?php else:?>
                                    <div class="listPriceBig">Pre-Order Price: <span class="listPriceBigPrice"><?php echo $this->helper('core')->currency($price,true,false); ?></span></div>
                            <?php endif;?>
                        <?php else: ?>
                            <?php if ($specialprice): ?>
                                    <div class="listPriceBig">Price: <span class="listPriceBigPrice"><?php echo $this->helper('core')->currency($specialprice,true,false); ?></span></div>
                                    <div class="listPriceSmall">Regular price: <span class="listPriceOld"><?php echo $this->helper('core')->currency($price,true,false); ?></span></div>
                            <?php else:?>
                                    <div class="listPriceBig">Price: <span class="listPriceBigPrice"><?php echo $this->helper('core')->currency($price,true,false); ?></span></div>
                            <?php endif;?>
                        <?php endif; ?> 
