<?php 
/**
 * See more VES_PdfPro_Block_Adminhtml_Version
 */
?>
<script type="text/javascript">
	$$('#nav li span').each(function(s){
		if(s.innerHTML == 'Easy PDF'){s.addClassName('easypdf-admin-menu');}
		if(s.innerHTML == 'Visit Website'){s.parentNode.href='http://www.easypdfinvoice.com';s.parentNode.target="_blank";}
	});
	Event.observe(window,'load',function(){
		$$('#system_config_tabs dd a span').each(function(s){
			if(s.innerHTML.trim()=='Easy PDF'){s.addClassName('easypdf-system-tab');}
		});
	});
</script>
<?php if($this->canDisplayNotice() || $this->canDisplayNews() || $this->canDisplayDefaultApiKeyMsg()):?>
	<div id="pdfpro-notifications">
		<?php if($this->canDisplayDefaultApiKeyMsg()):?>
			<div class="notification-global">
			    <strong>Easy PDF Invoice:</strong>
			    You need to set the default API Key for your website in <a href="<?php echo $this->getUrl('adminhtml/system_config/edit',array('section'=>'pdfpro'));?>">Configuration</a>
			</div>
		<?php endif;?>
		<?php if($this->canDisplayNotice()):?>
			<?php $serverVersion 	= $this->getServerVersion();?>
			<?php if($serverVersion && version_compare(Mage::helper('pdfpro')->getVersion(), $serverVersion,'<')):?>
				<div class="notification-global">
				    <strong>Easy PDF Invoice:</strong>
				    You are using the old version of Easy PDF (<?php echo Mage::helper('pdfpro')->getVersion();?>).The current version is <?php echo $serverVersion?>. Upgrade to latest version now! <a href="http://www.easypdfinvoice.com/blog/upgrade-easy-pdf-magento-extension/" target="_blank">How to upgrade?</a>
				</div>
			<?php endif;?>
		<?php endif;?>
		<?php if($this->canDisplayNews()):?>
			<?php $message 	= $this->getServerMessage();?>
			<?php if($message):?>
				<div class="notification-global notification-global-notice">
				    <strong>Easy PDF Invoice:</strong>
				    <?php echo $message;?>
				</div>
			<?php endif;?>
		<?php endif;?>
	</div>
<?php endif;?>