<?php
/**
 * @category    Mana
 * @package     Mana_Filters
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Category layered navigation state
 *
 * @see Mage_Catalog_Block_Layer_State
 */
?>
<?php $_filters = $this->getActiveFilters() ?>
<?php if(!empty($_filters)): ?>
<div class="currently">
    <?php if (Mage::helper('mana_filters')->renderHtml($this->getParentBlock(), 'YOUR SELECTION')) : ?>
    <p class="block-subtitle"><?php echo $this->__('Currently Shopping by:') ?></p>
    <?php endif; ?>
    <h4>YOUR SELECTION</h4>
    <ol>
    <?php foreach ($_filters as $_filter): ?>
    <?php if ($_html = $this->getValueHtml($_filter)) : ?>
        <?php echo $_html ?>
    <?php else : ?>
        <li>
            <a href="<?php echo $_filter->getRemoveUrl() ?>" title="<?php echo $this->__('Remove This Item') ?>" class="btn-remove"><img src="<?php echo $this->getSkinUrl('images/close.jpg');?>" alt="Remove This Item"></a>
            <!--<span class="label"><?php //echo $this->__($_filter->getName()) ?>:</span>--> <?php echo $_filter->getMShowSelected() ? $this->__('not') : '' ?> <?php echo $this->stripTags($_filter->getLabel()) ?>
        </li>
    <?php endif; ?>
    <?php endforeach; ?>
    </ol>
    
</div>
<?php endif; ?>
