<?php
/**
 * WDCA - Sweet Tooth
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the WDCA SWEET TOOTH POINTS AND REWARDS 
 * License, which extends the Open Software License (OSL 3.0).
 * The Sweet Tooth License is available at this URL: 
 *      http://www.wdca.ca/solutions_page_sweettooth/Sweet_Tooth_License.php
 * The Open Software License is available at this URL: 
 *      http://opensource.org/licenses/osl-3.0.php
 * 
 * DISCLAIMER
 * 
 * By adding to, editing, or in any way modifying this code, WDCA is 
 * not held liable for any inconsistencies or abnormalities in the 
 * behaviour of this code. 
 * By adding to, editing, or in any way modifying this code, the Licensee
 * terminates any agreement of support offered by WDCA, outlined in the 
 * provided Sweet Tooth License. 
 * Upon discovery of modified code in the process of support, the Licensee 
 * is still held accountable for any and all billable time WDCA spent 
 * during the support process.
 * WDCA does not guarantee compatibility with any other framework extension. 
 * WDCA is not responsbile for any inconsistencies or abnormalities in the
 * behaviour of this code if caused by other framework extension.
 * If you did not receive a copy of the license, please send an email to 
 * contact@wdca.ca or call 1-888-699-WDCA(9322), so we can send you a copy 
 * immediately.
 * 
 * @category   [TBT]
 * @package    [TBT_Rewards]
 * @copyright  Copyright (c) 2009 Web Development Canada (http://www.wdca.ca)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * Customer SideBar
 *
 * @category   TBT
 * @package    TBT_Rewards
 * @author     WDCA Sweet Tooth Team <contact@wdca.ca>
 */
?>

<div class="block box base-mini ad-reviews rewards-customer-sidebar" id="my_points">
    <div class="head block-title">
        <h4><strong><?php echo $this->__('Power Points') ?></strong></h4>
    </div>
    <div class="block-content">
        <?php if ($this->isCustomerLoggedIn()): ?>
            <?php if ($this->isSpendingAnyPoints()): ?>
            	<span><?php echo $this->__("You have")?></span><br/>
                <span><?php echo str_replace("Point","",str_replace("Points","Point",$this->getCustomerPoints())) ?> <?php echo $this->__("Power Points")?></span>
                <span><?php echo $this->__("to spend")?></span><br/>
            <?php else: ?>
                <div class="to_spend">
                    <?php if ($this->getCustomerPoints() == ""): ?>
                        <?php echo $this->__('You have no points to spend.') ?>
                    <?php else: ?>
                        <span><?php echo $this->__("You have")?></span><br/>
		                <span><?php echo str_replace("Point","",str_replace("Points","Point",$this->getCustomerPoints())) ?> <?php echo $this->__("Power Points")?></span>
		                <span><?php echo $this->__("to spend")?></span><br/>
                    <?php endif; ?>  
                </div>  			
            <?php endif; ?>
        <?php else: ?>
            <?php if ($this->isSpendingAnyPoints()): ?>
                <div class="to_spend">
                    <?php echo $this->__('To Spend: ') ?> <?php echo $this->getPointsSpending() ?>
                </div>
                <div class="warning">
                    <?php echo $this->__('You are trying to redeem points without being logged in.  Please log-in or create a new account to spend points.') ?>
                </div>
            <?php else: ?>
                
            <?php endif; ?>
        <?php endif; ?>
    	<div>
            <?php if ($this->isCustomerLoggedIn()): ?>
                <div class="bold-notice" style="margin-top: 10px; float: left;"><a href="<?php echo $this->getUrl('rewards/customer') ?>"><?php echo $this->__('Click HERE to manage your Power Points') ?></a></div>
            <?php else: ?>
                <div class="bold-notice"><a href="<?php echo $this->getUrl('rewards/customer') ?>"><?php echo $this->__('LOGIN or REGISTER') ?></a></div>
                <div class="notice">
                    <?php echo $this->__('to view your Power Points.') ?>
                </div>
                <div class="bottom-reward-text">
	            	<a href="<?php echo $this->getUrl("power-points")?>"><?php echo $this->__("Click HERE to learn about Power Points, how to earn them and how to use them to get 7% cashback on future orders")?></a>
	            </div>
            <?php endif; ?>
    	</div>
	</div>
</div>