<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->__('Download references')?></h3></td>
            <td class="a-right">
                <button onclick="getReferencesCsv()" class="scalable save" type="button"><span>Download reference records as CSV</span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <?php    
/*
    $resource = Mage::getSingleton('core/resource');

    $readConnection = $resource->getConnection('core_read');
    $table = $resource->getTableName('sales_order_custom');

    
    $query = 'SELECT increment_id, DATE_FORMAT(created_at,"%d-%m-%Y") AS created_at, CONCAT(customer_firstname," ",customer_lastname) AS credentials, GROUP_CONCAT(value) AS value FROM sales_order_custom AS custom LEFT JOIN sales_flat_order AS orders ON custom.order_id=orders.entity_id WHERE VALUE !="" GROUP BY increment_id
';

    $results = $readConnection->fetchAll($query);

    echo '<table border="1" bordercolor="#FFCC00" style="background-color:#FFFFCC" width="100%" cellpadding="3" cellspacing="3">';
	
    foreach ($results as $key => $value)
            {
                echo '<tr>';
                echo '<td>'.$value['increment_id'].'</td>';
                echo '<td>'.$value['created_at'].'</td>';
                echo '<td>'.$value['credentials'].'</td>';
                echo '<td>'.$value['value'].'</td>';
                echo '</tr>';
            }
            echo '</table>';
    //print_r($results);
    */
    ?>
</div>
<script type="text/javascript">
   
</script>