<?php
/**
 * Flint Technology Ltd
 *
 * This module was developed by Flint Technology Ltd (http://www.flinttechnology.co.uk).
 * For support or questions, contact us via http://www.flinttechnology.co.uk/store/contacts
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA bundled with this package in the file LICENSE.txt.
 * It is also available online at http://www.flinttechnology.co.uk/store/module-license-1.0
 *
 * @package     flint_feefo-ce-1.2.0.zip
 * @registrant  David Suter
 * @license     68561092-2FBC-43E2-8F1F-450A55AB97CE
 * @eula        Flint Module Single Installation License (http://www.flinttechnology.co.uk/store/module-license-1.0
 * @copyright   Copyright (c) 2012 Flint Technology Ltd (http://www.flinttechnology.co.uk)
 */

?>
<?php
if(Mage::getStoreConfig('flint_feefo/product/active')):
    $helper = Mage::helper('flint_feefo/Data');
    ?>
    <div class="flint_logo_product">
        <a onclick="popWin('<?php echo $helper->getLogoLink('product'); ?>', '<?php echo $this->__("Feefo reviews")?>', 'width=1000, height=600, toolbar=no, location=no, scrollbars=1'); return false;"  href="<?php echo $helper->getLogoLink('product'); ?>"  target="_blank">
            <img src="<?php echo $this->getSkinUrl('images/poweredbyfeefo.png'); ?>" alt="" />
        </a>
    </div>
    <?php
endif;
?>
