<?php
/**
 * Flint Technology Ltd
 *
 * This module was developed by Flint Technology Ltd (http://www.flinttechnology.co.uk).
 * For support or questions, contact us via http://www.flinttechnology.co.uk/store/contacts
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA bundled with this package in the file LICENSE.txt.
 * It is also available online at http://www.flinttechnology.co.uk/store/module-license-1.0
 *
 * @package     flint_feefo-ce-1.2.0.zip
 * @registrant  David Suter
 * @license     68561092-2FBC-43E2-8F1F-450A55AB97CE
 * @eula        Flint Module Single Installation License (http://www.flinttechnology.co.uk/store/module-license-1.0
 * @copyright   Copyright (c) 2012 Flint Technology Ltd (http://www.flinttechnology.co.uk)
 */

?>
<?php
$helper = Mage::helper('flint_feefo/Data');

if($dom = $helper->getReviews()):
    $feedbacks = $dom->getElementsByTagName('FEEDBACK');

    ?>
    <h2><img style="float:right" src="<?php echo $helper->getStarsSrc()?>"/></h2>

        <div class="std" id="feefo_reviews_block"">
           <?php

                if($feedbacks->length):
                   ?>
                    <table class="data-table" id="product-feefo-reviews"> 
                        <colgroup><col width="10%"><col  width="10%"><col width="50%"></colgroup>
                        <thead>
                            <tr>
                                <th><?php echo $this->__('Date') ?></th>
                                <th><?php echo $this->__('Score') ?></th>
                                <th><?php echo $this->__('Customer Comment') ?></th>
                                <th><?php echo $this->__('Our Response') ?> </th>
                            </tr>
                        <thead> 
                        <tbody> 
                   <?php
                    foreach($feedbacks as $feedback){
                        ?>
                            <tr>
                                <th>
                                    <?php print($feedback->getElementsByTagName('DATE')->item(0)->nodeValue); ?>
                                </th>
                                <td>
                                    <?php 
                                        if($feedback->getElementsByTagName('SERVICERATING')->length):
                                            print( 'Service: <br/>');
                                            foreach(str_split($feedback->getElementsByTagName('SERVICERATING')->item(0)->nodeValue) as $img){
                                                if($img === '+' || $img === '-') print('<img src="'.$this->getSkinUrl('images/flint_feefo'.$img.'.gif').'" />');
                                            }
                                            print('<br/>');
                                        endif;
                                        if($feedback->getElementsByTagName('PRODUCTRATING')->length):
                                            print( 'Product: <br/>');
                                            foreach(str_split($feedback->getElementsByTagName('PRODUCTRATING')->item(0)->nodeValue) as $img){
                                                if($img === '+' || $img === '-') print('<img src="'.$this->getSkinUrl('images/flint_feefo'.$img.'.gif').'" />'); 
                                            }
                                            print('<br/>');
                                        endif;
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    $shorCusCom = $feedback->getElementsByTagName('SHORTCUSTOMERCOMMENT')->item(0)->nodeValue;
                                    $CusCom = $feedback->getElementsByTagName('CUSTOMERCOMMENT')->item(0)->nodeValue;

                                    ?>
                                    <font id="shortCus<?php echo $feedback->getElementsByTagName('COUNT')->item(0)->nodeValue;?>"><?php print($shorCusCom); ?></font>
                                    <?php if($shorCusCom != $CusCom){ ?>
                                        <a href="<?php echo $this->__('Read More.') ?>" onclick="$('shortCus<?php echo $feedback->getElementsByTagName('COUNT')->item(0)->nodeValue;?>').style.display = 'none';this.style.display = 'none';$('longCus<?php echo $feedback->getElementsByTagName('COUNT')->item(0)->nodeValue;?>').style.display = '';return false;"><?php echo $this->__('Read More.') ?></a>
                                        <font id="longCus<?php echo $feedback->getElementsByTagName('COUNT')->item(0)->nodeValue;?>" style="display: none"><?php print($CusCom); ?></font>
                                    <?php } ?>
                                </td>
                                <td>
                                    <?php
                                    $shorVenCom = $feedback->getElementsByTagName('SHORTVENDORCOMMENT')->item(0)->nodeValue;
                                    $VenCom = $feedback->getElementsByTagName('VENDORCOMMENT')->item(0)->nodeValue;

                                    ?>
                                    <font id="short<?php echo $feedback->getElementsByTagName('COUNT')->item(0)->nodeValue;?>"><?php print($shorVenCom); ?></font>
                                    <?php if($shorVenCom != $VenCom){ ?>
                                        <a href="<?php echo $this->__('Read More.') ?>" onclick="$('short<?php echo $feedback->getElementsByTagName('COUNT')->item(0)->nodeValue;?>').style.display = 'none';this.style.display = 'none';$('long<?php echo $feedback->getElementsByTagName('COUNT')->item(0)->nodeValue;?>').style.display = '';return false;"><?php echo $this->__('Read More.') ?></a>
                                        <font id="long<?php echo $feedback->getElementsByTagName('COUNT')->item(0)->nodeValue;?>" style="display: none"><?php print($VenCom); ?></font>
                                    <?php } ?>
                                </td>
                            </tr>
                        <?php
                    }
                   ?>
                         </tbody>
                            <tr>
                                <td colspan="4" style="text-align: center;padding: 15px">
                                    <a href="<?php echo 'http://www.feefo.com/feefo/viewvendor.jsp?logon='.$helper->getConfig()->getConfigData('flint_feefo/general/logon'); ?>">
                                        <?php print($this->__('Read more reviews on Feefo')); ?>
                                    </a>
                                </td>
                            <tr>

                    </table>
                    <script type="text/javascript">decorateTable('product-feefo-reviews')</script>
                   <?php
                else:
                    ?>
                   <table class="data-table" id="product-feefo-reviews">  
                       <tr>
                           <th>
                               <?php echo  $this->__('This product has no reviews yet.'); ?>
                           </th>
                       </tr>
                   </table>
                   <script type="text/javascript">decorateTable('product-feefo-reviews')</script>
                   <?php
                endif;
             ?>

        </div>
<?php else: ?>
    <h2><?php echo $this->__('FeeFo Reviews') ?> <img style="float:right" src="<?php echo $helper->getStarsSrc()?>"/></h2>

        <div class="std" id="feefo_reviews_block">
            <?php echo  $this->__('Connection problem to Feefo server.'); ?>
        </div>
<?php endif; ?>

