<?php if($this->displayAllNotification()):?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__("Sweet Tooth Usage") ?></h4>
    </div>
    <fieldset class="np">
        <div style="padding:10px;">
            <?php if ($this->displayUsage()): ?>
                <div class="stpUsage">
                    <span style="width:<?php if ($this->getPercentComplete() >= "100"): ?>100%<?php else: ?><?php echo (($this->getPercentComplete())) ?>%<?php endif; ?>;"><?php echo $this->getPercentComplete(); ?>%</span>
                </div>
                <p class="stpStat">You've made <strong><?php echo $this->getTransactionsUsed(); ?></strong> transactions during your current billing period. <br />
                    <?php if ($this->displayBillingPeriod()): ?>
                        Billing Period: Starts <strong><?php echo $this->getBillingPeriodStart(); ?></strong> and ends <strong><?php echo $this->getBillingPeriodEnd(); ?></strong> <br />
                    <?php endif; ?>
                </p>
            <?php endif; ?>
            <?php echo $this->getNotificationsHtml(); ?>
        </div>
    </fieldset>
</div>
<?php endif;?>
